<head>
	<link rel="stylesheet" href="libraries/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="libraries/bootstrap/css/bootstrap-theme.min.css">
	<script src="libraries/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
	<h1>HOLA MUNDO</h1>
	<?php echo "HOLAAAAAAA"; ?>

	<div class="alert alert-success" role="alert">Alerta1</div>
	<div class="alert alert-info" role="alert">Alerta2</div>
	<div class="alert alert-warning" role="alert">Alerta3</div>
	<div class="alert alert-danger" role="alert">Alerta4</div>

	<div class="row">
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	  <div class="col-xs-12 col-sm-3 col-md-1">.col-xs-12 col-sm-3 col-md-1</div>
	</div>

</body>